credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "nexus"
          password: "{AQAAABAAAADQW/flyOQ+hqvouFuKR26VvpmRcCmkb6LC83TNLXLkImJjkwKGP8oOEXe9BNSRtSlKjhnNvUS0UIkp3LA3I6Fo6S/yFeIYO4mDaGntKmW/Xq9CgL5bTwdQW8BDFpfuiLuGFPR7Q+iCst7M+AMU7Y7F6zxOt48+ZdoQvLlyBoOMNASdYcu9FmY+Dw+pMs7iuvve3q1d4edSXFf72BhHoksWphPvggfRfx2R2QWtmiQReONAj5jenjCpgeI8UXwd0XHGc9Kg9J21D3Qrx9DVKS2x5SXwCpr4kzkEVMURITz0vBU=}"
          scope: GLOBAL
          username: "admin"
      - usernamePassword:
          description: "nexus_id"
          id: "nexus_id"
          password: "{AQAAABAAAADQcJKZXpzCyhgPq07h+RVjaIrjzeS8IY6HcmYVJYX5MNC3Ewla8ShjKzLdAbEeVA0BfW4unXLFvTKFVyKUn7Xqnl3X1Y9nwxe4iNcABugF1OZIVPGKVlwF1iIOss9BN0uYAXdRBnoFPPTd4CCcRjz3SdlqY5KDOPqtVQOiwReGYLlyMYs9V6P59xBSz9LAk5njY9f7jipkiQZ8x90A5ftcXv5VoQ/A5tU4W42+VgnIyhy5JH4xa7xJZNlinu2KKPYPqFhOU3/9Mx8M2Gdf71VcNzfyZPE+oVzpl66OkOHGGCk=}"
          scope: GLOBAL
          username: "admin"
          usernameSecret: true
    - credentials:
      - usernamePassword:
          description: "kgyuvraj"
          id: "kgyuvraj"
          password: "{AQAAABAAAAAwtZovlr96L1SuwSvkk+Om0fvy1nlom451ZTKaq2O5Tk0CU87LJJDfUlFJQ3s5R9vcsTAUQtzd+YChWCw+AH9Tvg==}"
          scope: GLOBAL
          username: "kgyuvraj"
      domain:
        description: "admin"
        name: "admin"
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  jdk:
    installations:
    - name: "openjdk-11"
      properties:
      - installSource:
          installers:
          - zip:
              subdir: "jdk-11.0.1"
              url: "https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz"
  maven:
    installations:
    - name: "Maven 3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.8.4"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
unclassified:
  globalConfigFiles:
    configs:
    - mavenSettings:
        comment: "User settings"
        content: |-
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">
            <servers>
              <server>
                <id>nexus</id>
                <username>admin</username>
                <password>kgb</password>
              </server>
              <server>
                <id>sm-snapshots</id>
                <username>admin</username>
                <password>kgb</password>
              </server>
              <server>
                <id>sm-releases</id>
                <username>admin</username>
                <password>kgb</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>nexus</id>
                <url>https://nexus.softwaremathematics.com/repository/maven-central</url>
                <mirrorOf>central</mirrorOf>
              </mirror>

              <mirror>
                <id>central</id>
                <name>central</name>
                <url>https://nexus.softwaremathematics.com</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>

          </settings>
        id: "mvn-settings"
        isReplaceAll: true
        name: "MySettings"
        providerId: "org.jenkinsci.plugins.configfiles.maven.MavenSettingsConfig"
  location:
    url: ${URL}
  resourceRoot:
    url: ${RESOURCEURL}
jobs:
  - script: |
      pipelineJob("SeedJob") {
      definition {
          cpsScm {
              scm {
                  git{
                    remote {
                      url("https://github.com/akshaygupta2208/JenkinsCASC.git")
                    }
                    branch("*/master")
                  }
              }
          }
        }
      }
