credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "nexus"
          password: "{AQAAABAAAAAQ3M5zF4M24FlsFPo9+Msu5l74eUg41LgQXSdCC+1jZmQ=}"
          scope: GLOBAL
          username: "admin"
      - usernamePassword:
          description: "nexus_id"
          id: "nexus_id"
          password: "{AQAAABAAAAAQ+eoDsMMpjLLT2FcQWOWRTSVI4yFrq0PzUv9ScIZVTZA=}"
          scope: GLOBAL
          username: "admin"
          usernameSecret: true
    - domain:
        description: "admin"
        name: "admin"
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false
unclassified:
  location:
    url: ${URL}
  resourceRoot:
    url: ${RESOURCEURL}
jobs:
  - script: |
      pipelineJob("SeedJob") {
      definition {
          cpsScm {
              scm {
                  git{
                    remote {
                      url("https://github.com/akshaygupta2208/JenkinsCASC.git")
                    }
                    branch("*/master")
                  }
              }
          }
        }
      }
