credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "nexus"
          password: "{AQAAABAAAACATTDuNr/5nMfMZPT5nFqqDi4EdyZgHlzdLzlYjPGJthZwHGgePVcMpgJvQprS8He7LPUBcHdoNHfgf0CH58do4wYQRFWEg2uwH9cYnNi8rNp+wcA0HNh6gEov+wW27IM3xMRIGdFCMRMU7HziP6iCmy0AzBLzwoCKZDIsu2IthqHL+DiNQ+GegZRqlAv164VT}"
          scope: GLOBAL
          username: "admin"
      - usernamePassword:
          description: "nexus_id"
          id: "nexus_id"
          password: "{AQAAABAAAACAIiTAaT3S3grcV1ccOgvkUMFqjAh69Rx7cip1keAa98WG/7IAfVCnlevdBLQPUddYg5A+eAZGHA+RbeOinGDlLMd95ssDqxkxTKD8Sx3ZgZNiJ6dWTUeDy34o89fAg7cJ2CXN28+09GcPuYIOOKjUZUVVOMo0jCTYnK4ym+spareSk9hvBkLFGDLWo+XbK/u0}"
          scope: GLOBAL
          username: "admin"
          usernameSecret: true
    - credentials:
      - usernamePassword:
          description: "kgyuvraj"
          id: "kgyuvraj"
          password: "{AQAAABAAAABwP72XlP9pedTqjlj4xRLB1SaDdgw6z67lIT9IzUFV6dMgQYmEKUvDxWW94K5df5E/0ZZTM2tRZG4lmehdvJiOOBmvz6e6jOJwIX55VLNo9tEEb1PCe9zvrJAI6vW8VoijB0JR355fgOPrXhFr6ihOGo+p/oSy2DTgQ4pnIndz+uY=}"
          scope: GLOBAL
          username: "kgyuvraj"
      domain:
        description: "admin"
        name: "admin"
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  jdk:
    installations:
    - name: "openjdk-11"
      properties:
      - installSource:
          installers:
          - zip:
              subdir: "jdk-11.0.1"
              url: "https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz"
  maven:
    installations:
    - name: "Maven 3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.8.4"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
unclassified:
  globalConfigFiles:
    configs:
    - mavenSettings:
        comment: "User settings"
        content: |-
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">
            <servers>
              <server>
                <id>nexus</id>
                <username>admin</username>
                <password>kgb</password>
              </server>
              <server>
                <id>sm-snapshots</id>
                <username>admin</username>
                <password>kgb</password>
              </server>
              <server>
                <id>sm-releases</id>
                <username>admin</username>
                <password>kgb</password>
              </server>
            </servers>
            <mirrors>
              <mirror>
                <id>central</id>
                <name>central</name>
                <url>https://nexus.softwaremathematics.com</url>
                <mirrorOf>*</mirrorOf>
              </mirror>
            </mirrors>

          </settings>
        id: "mvn-settings"
        isReplaceAll: true
        name: "MySettings"
        providerId: "org.jenkinsci.plugins.configfiles.maven.MavenSettingsConfig"
  location:
    url: ${URL}
  resourceRoot:
    url: ${RESOURCEURL}
jobs:
  - script: |
      pipelineJob("SeedJob") {
      definition {
          cpsScm {
              scm {
                  git{
                    remote {
                      url("https://github.com/akshaygupta2208/JenkinsCASC.git")
                    }
                    branch("*/master")
                  }
              }
          }
        }
      }
