# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
  #  - job_name: 'my_docker_metrics'
  #    static_configs:
  #      - targets:
  #          - 161.97.136.16:9417
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx ]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - http://prometheus.io    # Target to probe with http.
          - https://prometheus.io   # Target to probe with https.
          - http://example.com:8080 # Target to probe with http on port 8080.
          - http://194.163.159.164:9126/swagger-ui.html
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 38.242.198.101:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 161.97.136.16:4000
          - 194.163.159.164:4000
          - 38.242.154.127:4000
          - 185.207.250.107:4000
          - 38.242.198.101:4000
  - job_name: 'cont_metrics'
    static_configs:
      - targets:
          - 161.97.136.16:4001
          - 194.163.159.164:4001
          - 38.242.154.127:4001
          - 185.207.250.107:4001
          - 38.242.198.101:4001
  - job_name: 'jmx-exporter'
    static_configs:
      - targets:
          - 194.163.159.164:59082
          - 194.163.159.164:59087
          - 194.163.159.164:59090
          - 161.97.136.16:59132
          - 161.97.136.16:59108